#%RAML 1.0
title: Example
# resourceTypes:
#   collection: !include resource_types/collection.raml
baseUri: http://api.ramoulade.com/{version}/{object}
version:
  value: "1.0"
baseUriParameters:
  object:
    description: The object that you want
    type: string
    examples:
      - ball
      - box
    displayName: special_string
    enum: [ball, box, bar]
    facets:
      doIPlayWithIt?: boolean
protocols: [HTTPS, HTTP]
/products:
  type: collection
  description: All products
documentation:
 - title:
     value: Home
   content: |
     Welcome to the _Zencoder API_ Documentation. The _Zencoder API_
     allows you to connect your application to our encoding service
     and encode videos without going through the web  interface. You
     may also benefit from one of our
     [integration libraries](https://app.zencoder.com/docs/faq/basics/libraries)
     for different languages.
 - title: Legal
   content: !include docs/legal.markdown
